Repository valhalla/valhalla, pull requests merged in 2020-10, with the labels that each got.

#2638 README: Fix CircleCI badge to show status of master branch
  README.md
Labels: ci

#2640 remove notice from 2018
  CHANGELOG.md
  README.md
Labels: invalid

#2658 Fixed typo
  docs/meili/library_api.md
Labels: invalid

#2555 Shortest-ish
  CHANGELOG.md
  docs/api/turn-by-turn/api-reference.md
  proto/options.proto
  src/proto_conversions.cc
  src/sif/autocost.cc
  src/sif/bicyclecost.cc
  src/sif/dynamiccost.cc
  src/sif/motorcyclecost.cc
  src/sif/motorscootercost.cc
  src/sif/pedestriancost.cc
  src/sif/truckcost.cc
  src/worker.cc
  test/gurka/test_route.cc
  test/gurka/test_shortest.cc
  test/parse_request.cc
  valhalla/sif/costfactory.h
  valhalla/sif/dynamiccost.h
Labels: enhancement

#2665 Ambiguous Local Time when Within DST Change Hour
  CHANGELOG.md
  src/baldr/datetime.cc
  src/mjolnir/servicedays.cc
  test/gurka/test_time_tracking.cc
  valhalla/baldr/time_info.h
Labels: bug

#2670 fix reach counting of transition nodes
  CHANGELOG.md
  src/loki/reach.cc
  src/loki/search.cc
  test/reach.cc
Labels: bug
